#!/bin/bash -e
# use bash process substitution to prepend prelude to source file
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# read input first to check for errors accessing files
declare -a files=(
    "$DIR/../prelude.zero"
    "$DIR/../protoset.zero"
    "$DIR/../table.zero"
    "$DIR/scan.zero"
    "$DIR/ast.zero"
    "$DIR/lex.zero"
    "$DIR/serialize.zero"
    "$DIR/operators.zero"
    "$DIR/builtins.zero"
    "$DIR/desugar.zero"
    "$DIR/bind.zero"
    "$DIR/parse.zero"
    "$DIR/inference.zero"
)
chmod -f +w meta.tmp || true
cat ${files[@]} > meta.tmp
chmod -w meta.tmp
"$DIR/../../main" $* meta.tmp
