#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB="$DIR/../libraries"
PARSER="$DIR/../self-interpreter"
OUT="$DIR/main"

declare -a files=(
    "$LIB/operators.zero"
    "$LIB/prelude.zero"
    "$LIB/ralist.zero"
    "$LIB/store.zero"
    "$LIB/aatree.zero"
    "$LIB/table.zero"
    "$PARSER/lex.zero"
    "$PARSER/ast.zero"
    "$PARSER/errors.zero"
    "$PARSER/symbols.zero"
    "$PARSER/term.zero"
    "$PARSER/patterns.zero"
    "$PARSER/define.zero"
    "$PARSER/brackets.zero"
    "$PARSER/syntax.zero"
    "$PARSER/serialize.zero"
    "$PARSER/builtins.zero"
    "$PARSER/bind.zero"
    "$PARSER/parse.zero"
    "$PARSER/evaluate.zero"
    "$DIR/types.zero"
    "$DIR/show.zero"
    "$DIR/errors.zero"
    "$DIR/declarations.zero"
    "$DIR/inference.zero"
)

chmod -f +w "$OUT" || true
echo "#!../bootstrap-interpreter/main -t" > "$OUT"

# cat sources files and erase lines containing only comments to speed parsing
# note: can't remove blank lines because it would change line numbers in errors
# note: can't safely remove inline comments because they could be inside quotes
# note: also have to avoid erasing file markers
cat ${files[@]} | sed -e 's/^[ ]*# .*$//' >> "$OUT"
chmod -w "$OUT"
chmod +x "$OUT"

case "$1" in
        loc) cat "$OUT" | sed -e '/^#/d' | sed -e '/^[ ]*$/d' | wc -l;;
        test) time "$OUT" < "$OUT";;
esac
