#!/bin/sh

DIR=$(dirname "$0")
LIB="$DIR/../libraries"
PARSER="$DIR/../self-interpreter"
OUT="$DIR/main"

# BSD chmod still prints an error when the file is not found even with
# the -f flag, so we redirect stderr to /dev/null to hide that message
chmod -f +w "$OUT" 2> /dev/null || true
echo "#!../bootstrap-interpreter/main -t" > "$OUT"

# cat sources files and erase lines containing only comments to speed parsing
# note: can't remove blank lines because it would change line numbers in errors
# note: can't safely remove inline comments because they could be inside quotes
# note: also have to avoid erasing file markers
cat "$LIB/operators.zero" \
    "$LIB/prelude.zero" \
    "$LIB/ralist.zero" \
    "$LIB/array.zero" \
    "$LIB/aatree.zero" \
    "$LIB/table.zero" \
    "$PARSER/parse/lex/lex.zero" \
    "$PARSER/parse/ast.zero" \
    "$PARSER/parse/opp/errors.zero" \
    "$PARSER/parse/opp/opp.zero" \
    "$PARSER/parse/term.zero" \
    "$PARSER/parse/patterns.zero" \
    "$PARSER/parse/define.zero" \
    "$PARSER/parse/brackets.zero" \
    "$PARSER/parse/syntax.zero" \
    "$PARSER/serialize.zero" \
    "$PARSER/builtins.zero" \
    "$PARSER/parse/bind.zero" \
    "$PARSER/parse/parse.zero" \
    "$PARSER/evaluate.zero" \
    "$DIR/flatten.zero" \
    "$DIR/substitute.zero" \
    "$DIR/show.zero" \
    "$DIR/unify.zero" \
    "$DIR/inference.zero" |
sed -e 's/^[ ]*# .*$//' >> "$OUT"

chmod -w "$OUT"
chmod +x "$OUT"

case "$1" in
    loc) cat "$OUT" | sed -e '/^#/d' | sed -e '/^[ ]*$/d' | wc -l;;
    test) time "$OUT" < "$OUT";;
esac
