#!/bin/sh

OUT=${OUT:-"main"}
CC=${CC:-"cc"}

RED='\033[0;31m'
NOCOLOR='\033[0m'

# stack-protector should be off by default, but some linux distributions
# patch gcc to turn it on by default, so we explicitly disable it here; it
# will cause the nostdlib build to fail if it is enabled

# no-asynchronous-unwind-tables decreases the executable size and there seems
# to be no downside because the information will still be included when
# compiling with "-g" https://stackoverflow.com/a/26302715

# no-ident removes a small unneeded comment from the executable

# use this command to find all warnings not enabled by -Wall -Wextra
# gcc -Wall -Wextra -Q --help=warning | grep "\[disabled\]"
# note: -Wswitch-enum looks helpful, but doesn't allow default case
# to catch multiple cases, which we are using

WFLAGS="-std=c99 -Wpedantic -Wfatal-errors -Wall -Wextra \
-Wshadow -Winit-self -Wwrite-strings -Wconversion -Wcast-qual \
-Wredundant-decls -Wstrict-prototypes -Wmissing-prototypes"

SOURCES=$(find -L ./src ./lib -name "*.c" | grep -v "/libc/")
HEADERS=$(find -L ./src ./lib -name "*.h" | grep -v "/libc/")
OBJECTS="*.o"

echoexec() {
    echo "$@" && "$@"
}

clean() {
    rm -f $OBJECTS "$OUT"
}

is_up_to_date() {
    test -f "$1" && test -z "$(find -L . -name "*.[c|h]" -newer "$1")"
}

build_libc() {
    (cd lib/libc && ./make)
}

showsize() {
    output="$(wc -c "$OUT" | tr '\t' ' ' | tr -s ' ')"
    echo "$1 SIZE:\t$(echo "${output## }" | cut -d' ' -f1) bytes"
}

finish() {
    rm -f $OBJECTS
    echo
    echo "BUILD SUCCESSFUL"
    showsize "BINARY"
}

run_build() {
    echoexec "$CC" -o "$OUT" -Ilib $WFLAGS $CFLAGS $SOURCES &&
    finish
}

is_cc() {
    "$CC" -v 2>&1 | grep -q "^$1"
}

build() {
    if is_up_to_date "$OUT"; then
        return
    fi

    if is_cc "gcc" || is_cc "clang"; then
        run_build
    elif is_cc "Apple clang"; then
        run_build
    elif is_cc "tcc"; then
        WFLAGS="" CFLAGS="" run_build
    else
        WFLAGS="" run_build
    fi
}

config_optimized() {
    CFLAGS="-DNDEBUG -O3 -flto -fno-asynchronous-unwind-tables $CFLAGS"
}

config_static() {
    config_optimized
    CFLAGS="-static $CFLAGS"
}

config_debug() {
    CFLAGS="-g -Og -fsanitize=address,undefined -Wno-macro-redefined -D_FORTIFY_SOURCE=2 $CFLAGS"
}

config_custom() {
    printf "%b" "$RED"
    echo "NOTE: There has been some non-determinism in this build"
    echo "If the tests fail, try rebuilding and it should fix it,"
    echo "or you can change the optimization level from -Os to -O1"
    printf "%b\n" "$NOCOLOR"
    CFLAGS="-Os -nostdlib -nostdinc -isystem ./lib/libc/include/ -fno-builtin -flto $CFLAGS"
    SOURCES=$(find -L . -name "*.c")
    OBJECTS="*.o lib/libc/sys.o"
}

config_unused() {
    CFLAGS="-O0 -fdata-sections -ffunction-sections -Wl,--gc-sections,--print-gc-sections $CFLAGS"
}

xstrip() {
    # https://github.com/aunali1/super-strip
    if command -v sstrip > /dev/null; then
        sstrip "$OUT"
        showsize "STRIPPED"
    elif command -v strip > /dev/null; then
        if [ "$(uname)" == "Darwin" ]; then
            strip "$OUT"
        else
            strip -R .note -R .comment -R .eh_frame -R .eh_frame_hdr -s "$OUT"
        fi
        showsize "STRIPPED"
    else
        echo "Note: sstrip/strip not found, skipping strip"
    fi
}

lint() {
    # this is not usable due to bugs in splint
    splint +charint -redef -compdestroy -branchstate -mustfree \
        -temptrans -varuse -fcnuse -retvalother +matchanyintegral -unrecog \
        -Ilib $SOURCES
}

strip_comments() {
    if is_cc "gcc"; then
        gcc -fpreprocessed -dD -E -P "$@"
    else
        # doesn't strip out /* ... */ comments
        cat "$@" | grep -v '^[[:space:]]*//' | grep -v '^[[:space:]]*$'
    fi
}

sloc() {
    strip_comments $HEADERS $SOURCES | grep -v assert | wc -l
}

floc() {
    strip_comments $SOURCES | grep -v assert |
        ../tools/floc.sh | sort -n | ../tools/hist.sh
}

case "$1" in
    "") config_optimized && build;;
    test) config_optimized && build && time test/test.sh;;
    static) clean && config_static && build;;
    debug) clean && config_debug && build;;
    custom) clean && config_custom && build_libc && build;;
    unused) clean && config_unused && build_libc && build;;
    strip) xstrip;;
    lint) lint;;
    clean) clean;;
    sloc) sloc;;
    floc) floc;;
    tree) find lib src | sort | sed 's#[^/]*/#| #g';;
    graph) ../tools/depgraph.sh src | dot -o architecture.pdf -T pdf;;
    *) echo "usage error: unrecognized command \"$1\""; exit 1;;
esac
