#!/bin/sh
DIR=$(dirname "$0")
#stty -icanon
cat \
"$DIR/../libraries/operators.zero" \
"$DIR/../libraries/prelude.zero" \
"$DIR/../libraries/aatree.zero" \
"$DIR/../libraries/table.zero" \
"${1-"-"}" | "$DIR/main"
