version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run: apt-get update
      - run: apt-get -y install gcc time
      - checkout
      - run: cd bootstrap-interpreter && ./make test
