#!/bin/bash -e
# use bash process substitution to prepend prelude to source file
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB="$DIR/../libraries"
# read input first to check for errors accessing files
declare -a files=(
    "$LIB/operators.zero"
    "$LIB/prelude.zero"
    "$LIB/aatree.zero"
    "$LIB/protoset.zero"
    "$LIB/table.zero"
    "$DIR/lex.zero"
    "$DIR/ast.zero"
    "$DIR/errors.zero"
    "$DIR/symbols.zero"
    "$DIR/term.zero"
    "$DIR/type.zero"
    "$DIR/patterns.zero"
    "$DIR/define.zero"
    "$DIR/brackets.zero"
    "$DIR/syntax.zero"
    "$DIR/closure.zero"
    "$DIR/serialize.zero"
    "$DIR/builtins.zero"
    "$DIR/bind.zero"
    "$DIR/parse.zero"
    "$DIR/evaluate.zero"
    "$DIR/interpret.zero"
)
chmod -f +w meta.tmp || true

# cat sources files and erase lines containing only comments to speed parsing
# note: can't remove blank lines because it would change line numbers in errors
# note: can't safely remove inline comments because they could be inside quotes
# note: also have to avoid erasing file markers
cat ${files[@]} | sed -e 's/^[ ]*# .*$//' > meta.tmp
chmod -w meta.tmp
"$DIR/../bootstrap-interpreter/main" $* meta.tmp
