#!/bin/sh

DIR=$(dirname "$0")
LIB="$DIR/../libraries"
OUT="$DIR/main"

(cd ../bootstrap-interpreter || exit; ./make)

# BSD chmod still prints an error when the file is not found even with
# the -f flag, so we redirect stderr to /dev/null to hide that message
chmod -f +w "$OUT" 2> /dev/null || true
echo '#!../bootstrap-interpreter/main' > "$OUT"

# cat sources files and erase lines containing only comments to speed parsing
# note: can't remove blank lines because it would change line numbers in errors
# note: can't safely remove inline comments because they could be inside quotes
# note: also have to avoid erasing file markers
cat "$LIB/operators.zero" \
    "$LIB/prelude.zero" \
    "$LIB/ralist.zero" \
    "$LIB/array.zero" \
    "$LIB/aatree.zero" \
    "$LIB/table.zero" \
    "$DIR/parse/lex/lex.zero" \
    "$DIR/parse/opp/operator.zero" \
    "$DIR/parse/opp/shift.zero" \
    "$DIR/parse/ast.zero" \
    "$DIR/parse/term.zero" \
    "$DIR/parse/patterns.zero" \
    "$DIR/parse/define.zero" \
    "$DIR/parse/brackets.zero" \
    "$DIR/parse/syntax.zero" \
    "$DIR/parse/tokens.zero" \
    "$DIR/parse/bind.zero" \
    "$DIR/parse/parse.zero" \
    "$DIR/metacontext.zero" \
    "$DIR/resolve.zero" \
    "$DIR/serialize.zero" \
    "$DIR/builtins.zero" \
    "$DIR/evaluate.zero" \
    "$DIR/interpret.zero" |
sed -e 's/^[ ]*# .*$//' >> "$OUT"

chmod -w "$OUT"
chmod +x "$OUT"

case "$1" in
    loc) cat "$OUT" | sed -e '/^#/d' | sed -e '/^[ ]*$/d' | wc -l;;
    test) ../bootstrap-interpreter/test/test.sh meta;;
esac
